# fly.toml app configuration file generated for ape-genius on 2023-11-09T12:42:58-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ape-genius"
primary_region = "bos"

[build]

[http_service]
  min_machines_running = 1
  processes = ["app"]
