[
build
]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[
deploy
]
startCommand = "python telegram_bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[
variables
]
ENVIRONMENT = "production"
DEBUG = "False"