name: Deploy Landing Page

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'landing-page/package-lock.json'

    - name: Install Dependencies
      working-directory: ./landing-page
      run: |
        npm ci --legacy-peer-deps
        npm cache verify

    - name: Build
      working-directory: ./landing-page
      run: npm run build
      env:
        CI: true
        NODE_ENV: production

    - name: Setup Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        railway login --token ${{ secrets.RAILWAY_TOKEN }}

    - name: Deploy to Railway
      working-directory: ./landing-page
      run: |
        railway link ${{ secrets.RAILWAY_PROJECT_ID }}
        railway up \
          --service ${{ secrets.RAILWAY_LANDING_SERVICE_ID }} \
          --environment production \
          --detach
      env:
        RAILWAY_STATIC_ENVIRONMENT: true
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    # Backup deployment to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: landing-page/build
        branch: gh-pages
        clean: true

permissions:
  contents: write